name = "Ruby"
grammar = "ruby"
path_suffixes = [
    "rb",
    "Gemfile",
    "Guardfile",
    "rake",
    "Rakefile",
    "ru",
    "thor",
    "Capfile",
    "jbuilder",
    "rabl",
    "rxml",
    "builder",
    "gemspec",
    "rdoc",
    "pryrc",
    "simplecov",
    "Steepfile",
    "Podfile",
    "Brewfile",
    "Vagrantfile",
    "Puppetfile",
    "Fastfile",
    "Appfile",
    "Matchfile",
    "Cheffile",
    "Hobofile",
    "Appraisals",
    "Rantfile",
    "Berksfile",
    "Berksfile.lock",
    "Thorfile",
    "Dangerfile",
    "Deliverfile",
    "Scanfile",
    "Snapfile",
    "Gymfile"
]
first_line_pattern = '^#!.*\bruby\b'
line_comments = ["# "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]
collapsed_placeholder = "# ..."
tab_size = 2
scope_opt_in_language_servers = ["tailwindcss-language-server"]

[overrides.string]
word_characters = ["-"]
opt_into_language_servers = ["tailwindcss-language-server"]
