name = "HTML/ERB"
grammar = "embedded_template"
path_suffixes = ["html.erb"]
autoclose_before = ">})"
brackets = [{ start = "<", end = ">", close = true, newline = true }]
block_comment = ["<%#", "%>"]
word_characters = ["?", "!"]
